[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run vite-dev"
  port = 8080
  targetPort = 3000
  functionsPort = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "consolidate",
    "velocityjs",
    "dustjs-linkedin",
    "atpl",
    "liquor",
    "twig",
    "ejs",
    "eco",
    "jazz",
    "jqtpl",
    "hamljs",
    "hamlet",
    "whiskers",
    "haml-coffee",
    "hogan.js",
    "templayed",
    "handlebars",
    "underscore",
    "lodash",
    "walrus",
    "mustache",
    "just",
    "ect",
    "dot",
    "ractive",
    "mote",
    "swig",
    "razor",
    "react-dom/server",
    "arc-templates",
    "then-jade",
    "then-pug",
    "htmling",
    "pug",
    "marko",
    "teacup/lib/express",
    "slm",
    "squirrelly",
    "bracket-template",
    "nunjucks",
    "twing"
  ]
